<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CupriNet.Hosting" Version="0.6.2" />
    <PackageReference Include="CupriNet.Arcanum" Version="0.6.2" />
    <PackageReference Include="CupriNet.Core" Version="0.6.2" />
    <PackageReference Include="CupriNet.Rites" Version="0.6.2" />
    <PackageReference Include="CupriNet.Persistence" Version="0.6.2" />
    <PackageReference Include="CupriNet.Alembic.BouncyCastle" Version="0.6.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Banter.Protocol/Banter.Protocol.csproj" />
  </ItemGroup>
</Project>
